### ISSUE TITLE
יצירת עמוד לוח שנה

### ISSUE THREAD

**Issue by ronisch2** [MayaSasson/manager#3]
המערכת נפתחת על העמוד שמציג לוח שנה. לוח השנה מציג אירועים חשובים שקורים במדור ומעליו שורת קטגוריות שלכל קטגוריה צבע מסוים - הצבע יופיע בלוח השנה כאשר האירוע שמתרחש מתקשר לקטגוריה שלו.
![image](https://user-images.githubusercontent.com/62544146/77792913-425e0380-707a-11ea-950d-74115f0ac540.png)

**הערות:**
להשתמש בקומפוננטה של לוח שנה בvuetify
אין צורך להשתמש במידע אמיתי - זה יהיה במשימה אחרת

**Comment by RoeiRom** [comment]
יש בעיות של אסינכרוניות שצריך לתקן, לא לאשר עד הודעה חדשה!

**Comment by RoeiRom** [comment]
אפשר לאשר
