### ISSUE TITLE
תפריט עליון

### ISSUE THREAD

**Issue by MayaSasson** [MayaSasson/manager#5]
במערכת שלנו יהיה תפריט עליון שמטרתו לעבור בין הפיצ'רים של המערכת, שנראה כך:
![image](https://user-images.githubusercontent.com/62544146/77639387-611ca700-6f61-11ea-8ab2-afb4f0e2510c.png)

לתפריט יש שני חלקים:
1. לוגו המערכת מצד ימין:

![image](https://user-images.githubusercontent.com/62544146/77639283-2d418180-6f61-11ea-8c04-2209f078db4e.png)

2. תפריט הפיצ'רים במערכת, שמורכב מהאייקונים הבאים:
![image](https://user-images.githubusercontent.com/62544146/77641304-83fc8a80-6f64-11ea-8b03-203ed090ea7c.png) - order food
![image](https://user-images.githubusercontent.com/62544146/77641434-bd34fa80-6f64-11ea-9fc9-a5a07d599572.png) - whats new
![image](https://user-images.githubusercontent.com/62544146/77641466-c8882600-6f64-11ea-8ee8-3df0098e99be.png) - calendar
![image](https://user-images.githubusercontent.com/62544146/77641497-d2aa2480-6f64-11ea-84eb-a89ca72cf2a0.png) - download
![image](https://user-images.githubusercontent.com/62544146/77641527-dccc2300-6f64-11ea-852c-f23068896906.png) - shekem list

התנהגות התפריט:
1. כאשר בוחרים קטגוריה מסוימת, האייקון נצבע באפרפר כמו בתמונה.
2. כאשר נכנסים למערכת האופציה של לוח השנה בחורה אוטומטית.

**הערות:**
1. יש לממש את כל זה בקובץ default.vue.
2. יש לממש את התפריט עם routes כמובן - אפשר לבחור את השמות של הroutes לפי מה שבאלכם, רק שיהיו ברורים וקצרים.

**Comment by RoeiRom** [comment]
כשיש hover על קטגוריה מסויימת יהיה צבע שונה?

**Comment by MayaSasson** [comment]
כן, הצבע שיש על האייקון של הלוח שנה

**Comment by RoeiRom** [comment]
סגור
