### ISSUE TITLE
בניית DB

### ISSUE THREAD

**Issue by MayaSasson** [MayaSasson/manager#8]
יש להרים שרת DB מקומי מסוג Postgres שיכיל מידע שאנחנו צריכים למערכת.
איך ה-DB אמור להראות:
![image](https://user-images.githubusercontent.com/62448339/77774551-5266ea80-705c-11ea-9b19-ee5ae5776b47.png)

**הערות:**
יש להכניס מידע פיקטיבי שאפשר יהיה לעבוד איתו

**Comment by RoeiRom** [comment]
בוצע merge
